#!/usr/bin/env node
/**
 * dev-scope — exclude disabled extensions from lint and typecheck.
 *
 * extmgr switches an extension off by renaming its entry file to
 * `<entry>.disabled`; the rest of its tree stays plain `.ts`, so the dev tools
 * would keep checking code that is not loaded. This mirrors extmgr's discovery
 * (agent/extensions/extmgr/src/discovery.ts) and writes the off-set to
 * `tsconfig.devscope.json`, read by `tsconfig.json` (extends) and
 * `eslint.config.mjs` (global ignores) so both tools share one source of truth.
 * Regenerated by the typecheck, lint, lint:fix and prepare scripts.
 *
 * The fragment carries the whole exclude list: a tsconfig that declares its own
 * `exclude` discards the inherited one, so the static base cannot stay in
 * tsconfig.json. Entries are globs so both tools consume them verbatim.
 *
 * Only directories are considered — a top-level extension file has no tree to
 * exclude, and its `.disabled` form matches no include pattern anyway.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(REPO_ROOT, "tsconfig.devscope.json");
const DISABLED_SUFFIX = ".disabled";
const ROOTS = ["agent/extensions", ".pi/extensions"];
const FALLBACK_ENTRIES = ["index.ts", "index.js"];
/** Always-excluded build/vendor trees; see the extends note above. */
const BASE_EXCLUDES = ["**/node_modules", "**/dist", "**/build"];

/** Repo-relative glob covering `path` and everything under it. */
const under = (path) => `${relative(REPO_ROOT, path).split(sep).join("/")}/**`;

/** The manifest's declared entry, or "" when the manifest declares none. */
function declaredEntry(dir) {
    try {
        const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
        const declared = manifest.pi?.extensions;
        const entry = Array.isArray(declared) && declared.length > 0 ? declared[0] : manifest.main;
        return typeof entry === "string" ? entry.replace(/^\.\//, "") : "";
    } catch {
        return "";
    }
}

/**
 * Glob covering `dir` while its entry file is switched off, else undefined.
 * A declared entry is authoritative; `index.ts`/`index.js` is the fallback only
 * when nothing is declared. A directory with no entry at all is a shared
 * library rather than an extension, so it is never excluded.
 */
function disabledGlob(dir) {
    const entry =
        declaredEntry(dir) ||
        FALLBACK_ENTRIES.find((name) => {
            const active = join(dir, name);
            return existsSync(active) || existsSync(active + DISABLED_SUFFIX);
        });
    if (!entry || existsSync(join(dir, entry))) return undefined;
    return existsSync(join(dir, entry + DISABLED_SUFFIX)) ? under(dir) : undefined;
}

const disabled = ROOTS.flatMap((root) => {
    const absolute = join(REPO_ROOT, root);
    if (!existsSync(absolute)) return [];
    return readdirSync(absolute, { withFileTypes: true })
        .filter((item) => item.isDirectory() && !item.name.startsWith("."))
        .map((item) => disabledGlob(join(absolute, item.name)))
        .filter(Boolean);
}).sort();

const contents = `${JSON.stringify({ exclude: [...BASE_EXCLUDES, ...disabled] }, null, 2)}\n`;

// Write only on change, so a steady scope never invalidates tool caches.
const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : null;
if (current !== contents) writeFileSync(OUTPUT, contents, "utf8");

if (!process.argv.includes("--quiet")) {
    console.log(
        `dev-scope: ${disabled.length} extension(s) excluded from lint/typecheck (${current === contents ? "unchanged" : "written"})`,
    );
    for (const path of disabled) console.log(`  - ${path}`);
}
