/**
 * GENERATED BY .script/merge.mjs - do not edit by hand; edit the sources it lists instead.
 * Merged to cut boot cost: jiti pays ~19ms per module regardless of size.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { ExtensionContext, ThemeColor, ExtensionAPI } from "@earendil-works/pi-coding-agent";

// ============================================================
// from: ..\..\pi-speeed\src\config.ts
// ============================================================

export const CONFIG_PATH = join(homedir(), ".pi", "agent", "pi-speeed.json");
export type CountStrategy = "estimate" | "direct";
export type Config = {
    enabled: boolean;
    label: string;
    workingPrefix: string;
    icon: string;
    renderIntervalMs: number;
    speedAnimationMs: number;
    slidingWindowMs: number;
    minReliableDurationMs: number;
    maxDisplayTokS: number;
    useProviderTokens: boolean;
    countStrategy: CountStrategy;
};
export const DEFAULT_CONFIG: Config = {
    enabled: true,
    label: "tok/s",
    workingPrefix: "Working...",
    icon: "✦",
    renderIntervalMs: 250,
    speedAnimationMs: 1800,
    slidingWindowMs: 1000,
    minReliableDurationMs: 1000,
    maxDisplayTokS: 500,
    useProviderTokens: true,
    countStrategy: "estimate",
};
function asRecord(value: unknown): Record<string, unknown> {
    return value !== null && typeof value === "object" && !Array.isArray(value)
        ? (value as Record<string, unknown>)
        : {};
}
function booleanFrom(raw: unknown, fallback: boolean) {
    return typeof raw === "boolean" ? raw : fallback;
}
function stringFrom(raw: unknown, fallback: string) {
    return typeof raw === "string" ? raw : fallback;
}
function positiveNumberFrom(raw: unknown, fallback: number) {
    return typeof raw === "number" && Number.isFinite(raw) && raw > 0 ? raw : fallback;
}
function countStrategyFrom(raw: unknown, fallback: CountStrategy): CountStrategy {
    return raw === "estimate" || raw === "direct" ? raw : fallback;
}
export function normalizeConfig(raw: unknown): Config {
    const input = asRecord(raw);
    const config: Config = {
        enabled: booleanFrom(input.enabled, DEFAULT_CONFIG.enabled),
        label: stringFrom(input.label, DEFAULT_CONFIG.label),
        workingPrefix: stringFrom(input.workingPrefix, DEFAULT_CONFIG.workingPrefix),
        icon: stringFrom(input.icon, DEFAULT_CONFIG.icon),
        renderIntervalMs: positiveNumberFrom(
            input.renderIntervalMs,
            DEFAULT_CONFIG.renderIntervalMs,
        ),
        speedAnimationMs: positiveNumberFrom(
            input.speedAnimationMs,
            DEFAULT_CONFIG.speedAnimationMs,
        ),
        slidingWindowMs: positiveNumberFrom(input.slidingWindowMs, DEFAULT_CONFIG.slidingWindowMs),
        minReliableDurationMs: positiveNumberFrom(
            input.minReliableDurationMs,
            DEFAULT_CONFIG.minReliableDurationMs,
        ),
        maxDisplayTokS: positiveNumberFrom(input.maxDisplayTokS, DEFAULT_CONFIG.maxDisplayTokS),
        useProviderTokens: booleanFrom(input.useProviderTokens, DEFAULT_CONFIG.useProviderTokens),
        countStrategy: countStrategyFrom(input.countStrategy, DEFAULT_CONFIG.countStrategy),
    };
    return config;
}
export function loadConfig(): Config {
    try {
        if (!existsSync(CONFIG_PATH)) return { ...DEFAULT_CONFIG };
        return normalizeConfig(JSON.parse(readFileSync(CONFIG_PATH, "utf8")));
    } catch {
        return { ...DEFAULT_CONFIG };
    }
}
export function saveConfig(config: Config) {
    writeFileSync(CONFIG_PATH, `${JSON.stringify(normalizeConfig(config), null, 2)}\n`);
}

// ============================================================
// from: ..\..\pi-speeed\src\display.ts
// ============================================================

type Theme = ExtensionContext["ui"]["theme"];
// Two-character icons starting with a badge opener glyph are rendered as a
// wrapping pair (opener ... closer); every other value is a plain prefix.
const BADGE_CLOSERS: Record<string, string> = {
    "\uE0B6": "\uE0B4",
    "\uE0C7": "\uE0C6",
};
function styledSpeedText(theme: Theme, config: Config, speed: number | null) {
    const value = speed === null ? "--" : speed.toFixed(1);
    const valueTone = speed === null ? "dim" : speedTone(speed);
    return `${theme.fg(valueTone, value)} ${theme.fg("dim", config.label)}`;
}
/** Speed tier colors: a slow stream reads red, a saturated one green. The tiers
 *  are half-open, so a value landing on a boundary takes the faster tier
 *  (15 → orange, 30 → yellow, 60 → blue, 100 → green). `syntaxNumber` is the
 *  theme's orange; `success` is the fastest tier's tone. */
function speedTone(speed: number): ThemeColor {
    if (speed < 15) return "error";
    if (speed < 30) return "syntaxNumber";
    if (speed < 60) return "warning";
    if (speed < 100) return "accent";
    return "success";
}
function styledSpeedBadge(theme: Theme, config: Config, speed: number | null) {
    const speedText = styledSpeedText(theme, config, speed);
    const icon = config.icon.trim();
    if (icon === "none" || icon === "") return speedText;
    if (icon.length === 2 && BADGE_CLOSERS[icon[0]] === icon[1])
        return `${theme.fg("accent", icon[0])}${speedText}${theme.fg("accent", icon[1])}`;
    return `${theme.fg("accent", icon)} ${speedText}`;
}
export function renderStyledWorkingTokS(theme: Theme, config: Config, speed: number | null) {
    return `${theme.fg("muted", config.workingPrefix)}  ${styledSpeedBadge(theme, config, speed)}`;
}
export function clearUi(ctx: ExtensionContext) {
    if (!ctx.hasUI) return;
    ctx.ui.setWorkingMessage();
}

// ============================================================
// from: ..\..\pi-speeed\src\engine.ts
// ============================================================

export type TokenEvent = { time: number; tokens: number };
const COMPACTION_THRESHOLD = 5000;
export type EngineConfig = Pick<
    Config,
    | "slidingWindowMs"
    | "minReliableDurationMs"
    | "maxDisplayTokS"
    | "useProviderTokens"
    | "countStrategy"
>;
export function estimateTokensFromDelta(text: string, strategy: Config["countStrategy"]) {
    if (!text) return 0;
    if (strategy === "direct") return 1;
    const matches = text.match(/\w+|[^\s\w]/g);
    return matches ? matches.length : 0;
}
export class TokenSpeedEngine {
    private _isStreaming = false;
    private _tokenCount = 0;
    private _startTime = 0;
    private _endTime = 0;
    private _events: TokenEvent[] = [];
    private _windowStartIndex = 0;
    private _countedUsageOutput = 0;
    private _lastStableTokS = 0;
    constructor(private _config: EngineConfig) {}
    updateConfig(config: EngineConfig) {
        this._config = config;
    }
    get isStreaming() {
        return this._isStreaming;
    }
    get elapsedMs() {
        if (this._startTime === 0) return 0;
        if (this._isStreaming) return Date.now() - this._startTime;
        return this._endTime - this._startTime;
    }
    get avgTokS() {
        const elapsedSec = this.elapsedMs / 1000;
        if (elapsedSec <= 0) return 0;
        return this._tokenCount / elapsedSec;
    }
    sanitizeTokS(value: number | null, durationMs = this.elapsedMs) {
        if (value === null || !Number.isFinite(value) || value <= 0) return null;
        if (durationMs < this._config.minReliableDurationMs) return null;
        if (value > this._config.maxDisplayTokS) return null;
        return value;
    }
    /** Sliding-window tok/s; suppresses unreliable burst-only readings. */
    get tokS() {
        const candidate = this.rawTokS;
        const stable = this.sanitizeTokS(candidate);
        if (stable !== null) this._lastStableTokS = stable;
        return this._lastStableTokS;
    }
    /** Unsanitized sliding-window tok/s; useful for tests and diagnostics. */
    get rawTokS() {
        if (this.elapsedMs < this._config.slidingWindowMs) return this.avgTokS;
        if (!this._isStreaming) return this.avgTokS;
        const now = Date.now();
        const windowStart = now - this._config.slidingWindowMs;
        while (
            this._windowStartIndex < this._events.length &&
            this._events[this._windowStartIndex].time < windowStart
        ) {
            this._windowStartIndex++;
        }
        if (this._windowStartIndex >= this._events.length) return this.avgTokS;
        let windowTokenCount = 0;
        for (let i = this._windowStartIndex; i < this._events.length; i++) {
            windowTokenCount += this._events[i].tokens;
        }
        if (windowTokenCount === 0) return this.avgTokS;
        const windowDuration = (now - this._events[this._windowStartIndex].time) / 1000;
        if (windowDuration <= 0) return 0;
        return windowTokenCount / windowDuration;
    }
    start() {
        this._tokenCount = 0;
        this._isStreaming = true;
        this._startTime = Date.now();
        this._endTime = Date.now();
        this._events = [];
        this._windowStartIndex = 0;
        this._countedUsageOutput = 0;
        this._lastStableTokS = 0;
    }
    stop() {
        this._isStreaming = false;
        this._endTime = Date.now();
        this._events = [];
        this._windowStartIndex = 0;
    }
    recordDelta(delta: string, usageOutput?: number) {
        if (!this._isStreaming) return;
        if (
            this._config.useProviderTokens &&
            usageOutput !== undefined &&
            usageOutput > this._countedUsageOutput
        ) {
            this.recordTokens(usageOutput - this._countedUsageOutput);
            this._countedUsageOutput = usageOutput;
            return;
        }
        this.recordTokens(estimateTokensFromDelta(delta, this._config.countStrategy));
    }
    reconcileTotal(tokens: number) {
        if (tokens > 0) this._tokenCount = tokens;
    }
    recordTokens(tokens: number) {
        if (!this._isStreaming || tokens <= 0) return;
        this._tokenCount += tokens;
        this._events.push({ time: Date.now(), tokens });
        if (this._windowStartIndex >= COMPACTION_THRESHOLD) this.compact();
    }
    private compact() {
        if (this._windowStartIndex === 0) return;
        this._events = this._events.slice(this._windowStartIndex);
        this._windowStartIndex = 0;
    }
}

// ============================================================
// from: ..\..\pi-speeed\src\settings.ts
// ============================================================

async function promptText(ctx: ExtensionContext, title: string, current: string) {
    const value = await ctx.ui.input(title, current);
    return value === undefined ? current : value;
}
async function promptNumber(ctx: ExtensionContext, title: string, current: number) {
    const value = await ctx.ui.input(title, String(current));
    if (value === undefined) return current;
    const parsed = Number(value);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : current;
}
export async function openSettings(
    ctx: ExtensionContext,
    getConfig: () => Config,
    setConfig: (config: Config) => void,
    applyConfig: () => void,
) {
    while (true) {
        let config = getConfig();
        const choice = await ctx.ui.select("pi-speeed settings", [
            `Enabled: ${config.enabled ? "on" : "off"}`,
            `Label: ${config.label}`,
            `Working prefix: ${config.workingPrefix}`,
            `Speed badge icon: ${config.icon}`,
            `Render interval: ${config.renderIntervalMs}ms`,
            "Reset defaults",
            "Done",
        ]);
        if (!choice || choice === "Done") return;
        config = { ...config };
        if (choice.startsWith("Enabled:")) config.enabled = !config.enabled;
        else if (choice.startsWith("Label:"))
            config.label = await promptText(ctx, "Speed label", config.label);
        else if (choice.startsWith("Working prefix:"))
            config.workingPrefix = await promptText(ctx, "Working prefix", config.workingPrefix);
        else if (choice.startsWith("Speed badge icon:"))
            config.icon = await promptText(
                ctx,
                "Speed badge icon (empty or none = no icon)",
                config.icon,
            );
        else if (choice.startsWith("Render interval:"))
            config.renderIntervalMs = await promptNumber(
                ctx,
                "Render interval ms",
                config.renderIntervalMs,
            );
        else if (choice === "Reset defaults") {
            if (await ctx.ui.confirm("Reset pi-speeed?", "Restore default settings?"))
                config = { ...DEFAULT_CONFIG };
        }
        setConfig(config);
        applyConfig();
        ctx.ui.notify("pi-speeed config saved", "info");
    }
}

// ============================================================
// from: ..\..\pi-speeed\src\speed-animation.ts
// ============================================================

export class SpeedAnimator {
    private from: number | null = null;
    private target: number | null = null;
    private startedAt = 0;
    constructor(private durationMs: number) {}
    updateDuration(durationMs: number) {
        this.durationMs = durationMs;
    }
    reset(value: number | null = null, now = Date.now()) {
        this.from = value;
        this.target = value;
        this.startedAt = now;
    }
    setTarget(target: number | null, now = Date.now()) {
        if (target === null) {
            this.reset(null, now);
            return null;
        }
        const current = this.value(now);
        if (current === null) {
            this.reset(target, now);
            return target;
        }
        if (this.target !== null && Math.abs(target - this.target) < 0.05) return current;
        this.from = current;
        this.target = target;
        this.startedAt = now;
        return current;
    }
    value(now = Date.now()) {
        if (this.target === null) return null;
        if (this.from === null || this.durationMs <= 0) return this.target;
        const progress = Math.max(0, Math.min(1, (now - this.startedAt) / this.durationMs));
        if (progress >= 1) {
            this.from = this.target;
            return this.target;
        }
        return this.from + (this.target - this.from) * progress;
    }
    isAnimating(now = Date.now()) {
        return (
            this.target !== null &&
            this.from !== null &&
            Math.abs(this.target - this.from) >= 0.05 &&
            now - this.startedAt < this.durationMs
        );
    }
}

// ============================================================
// from: ..\..\pi-speeed\src\speed-tracker.ts
// ============================================================

export class SpeedTracker {
    private readonly engine: TokenSpeedEngine;
    private lastStableTokS: number | null = null;
    constructor(config: Config) {
        this.engine = new TokenSpeedEngine(config);
    }
    updateConfig(config: Config) {
        this.engine.updateConfig(config);
    }
    get isStreaming() {
        return this.engine.isStreaming;
    }
    get lastTokS() {
        return this.lastStableTokS;
    }
    startMessage() {
        this.engine.start();
    }
    recordDelta(delta: string, usageOutput?: number) {
        this.engine.recordDelta(delta, usageOutput);
    }
    stopMessage() {
        if (this.engine.isStreaming) this.engine.stop();
    }
    liveTokS() {
        const speed = this.engine.tokS;
        return speed > 0 ? speed : this.lastStableTokS;
    }
    finishMessage(outputTokens: number) {
        if (!this.engine.isStreaming) return;
        this.engine.reconcileTotal(outputTokens);
        this.lastStableTokS = this.engine.sanitizeTokS(this.engine.avgTokS, this.engine.elapsedMs);
        this.engine.stop();
    }
}

// ============================================================
// from: ..\..\pi-speeed\src\index.ts
// ============================================================

export default function (pi: ExtensionAPI) {
    let config: Config = loadConfig();
    let lastRenderedAt = 0;
    const speedTracker = new SpeedTracker(config);
    const liveSpeedAnimator = new SpeedAnimator(config.speedAnimationMs);
    let liveAnimationTimer: ReturnType<typeof setInterval> | undefined;
    function renderWorking(ctx: ExtensionContext, speed = speedTracker.liveTokS()) {
        if (!config.enabled || !ctx.hasUI) return;
        ctx.ui.setWorkingMessage(renderStyledWorkingTokS(ctx.ui.theme, config, speed));
    }
    function applyConfig(ctx: ExtensionContext) {
        saveConfig(config);
        speedTracker.updateConfig(config);
        liveSpeedAnimator.updateDuration(config.speedAnimationMs);
        if (!config.enabled) {
            stopLiveAnimation();
            clearUi(ctx);
        }
    }
    function renderLiveSpeed(ctx: ExtensionContext) {
        const speed = speedTracker.liveTokS();
        const displayedSpeed = liveSpeedAnimator.setTarget(speed);
        renderWorking(ctx, displayedSpeed);
    }
    function stopLiveAnimation() {
        if (!liveAnimationTimer) return;
        clearInterval(liveAnimationTimer);
        liveAnimationTimer = undefined;
    }
    function startLiveAnimation(ctx: ExtensionContext) {
        if (liveAnimationTimer || !ctx.hasUI) return;
        liveAnimationTimer = setInterval(() => {
            if (!config.enabled || !speedTracker.isStreaming) {
                stopLiveAnimation();
                return;
            }
            renderLiveSpeed(ctx);
        }, config.renderIntervalMs);
    }
    function resetWorkingUi(ctx: ExtensionContext) {
        liveSpeedAnimator.reset(speedTracker.lastTokS);
        renderWorking(ctx, speedTracker.lastTokS);
    }
    pi.on("session_start", async () => {
        stopLiveAnimation();
        config = loadConfig();
        speedTracker.updateConfig(config);
        liveSpeedAnimator.updateDuration(config.speedAnimationMs);
    });
    pi.on("agent_start", async (_event, ctx) => {
        if (!config.enabled) return;
        resetWorkingUi(ctx);
    });
    pi.on("turn_start", async (_event, ctx) => {
        if (!config.enabled) return;
        resetWorkingUi(ctx);
    });
    pi.on("message_start", async (event, ctx) => {
        if (!config.enabled || event.message?.role !== "assistant") return;
        speedTracker.startMessage();
        liveSpeedAnimator.reset(speedTracker.lastTokS);
        startLiveAnimation(ctx);
        lastRenderedAt = 0;
    });
    pi.on("message_update", async (event, ctx) => {
        if (!config.enabled || event.message.role !== "assistant" || !speedTracker.isStreaming)
            return;
        const ev = event.assistantMessageEvent;
        if (ev.type === "text_delta" || ev.type === "thinking_delta") {
            speedTracker.recordDelta(ev.delta, ev.partial?.usage?.output);
        }
        if (ev.type === "start") resetWorkingUi(ctx);
        const now = Date.now();
        if (now - lastRenderedAt < config.renderIntervalMs && ev.type !== "done") return;
        lastRenderedAt = now;
        renderLiveSpeed(ctx);
    });
    pi.on("message_end", async (event) => {
        if (!config.enabled || event.message.role !== "assistant") return;
        speedTracker.finishMessage(event.message.usage?.output ?? 0);
    });
    pi.on("turn_end", async () => {
        speedTracker.stopMessage();
        stopLiveAnimation();
    });
    pi.on("agent_end", async (_event, ctx) => {
        speedTracker.stopMessage();
        stopLiveAnimation();
        if (ctx.hasUI) ctx.ui.setWorkingMessage();
    });
    pi.on("session_shutdown", async (_event, ctx) => {
        stopLiveAnimation();
        clearUi(ctx);
    });
    pi.registerCommand("pi-speeed", {
        description: "Open pi-speeed settings",
        handler: async (_args, ctx) => {
            await openSettings(
                ctx,
                () => config,
                (next) => (config = next),
                () => applyConfig(ctx),
            );
        },
    });
}
