/**
 * GENERATED BY .script/merge.mjs - do not edit by hand; edit the sources it lists instead.
 * Merged to cut boot cost: jiti pays ~19ms per module regardless of size.
 */
import { getMarkdownTheme } from "@earendil-works/pi-coding-agent";
import { Markdown, Text, type Component } from "@earendil-works/pi-tui";
import {
    type BoxTheme,
    formatElapsedMetric,
    getTextOutput,
    renderBoxedToolCall,
    renderBoxedToolResult,
    formatBoxedRunningStatus,
    formatCompactCount,
    formatToolOutputLine,
    selectRenderLines,
    formatToolName,
    RUNNING_TITLE_GLYPH,
} from "./pistyle/shared/index.js";
import {
    type BoxedToolContext,
    type BoxedToolResult,
    displayPath,
    noteBoxedCallState,
    noteBoxedResultPhase,
    noteExecutionStart,
    stateElapsedMs,
    isResultSeen,
    getToolsRenderConfig,
} from "./pistyle/features/tools/boxed/index.js";
import { registerCleanup } from "./support.js";

// from: db-query-card.ts

/**
 * Boxed card for db-viewer's query tools (fork addition — not vendored pi-style).
 *
 * db-viewer ships only a `renderResult` (a markdown box table) for these tools and
 * this fork's renderer patch bypasses it: without this card they fall to the
 * generic fallback, which loses the table look and prints every argument —
 * including the credentials inside `connectionString`.
 */
/** db-viewer tool name → card title (mirrors the label on its tool definitions). */
const DB_QUERY_TOOL_LABELS: Record<string, string> = {
    query_sqlite: "Query SQLite",
    query_mysql: "Query MySQL",
};
/** SQL lines shown on a collapsed call card; expanding the block reveals the rest. */
const COLLAPSED_QUERY_LINES = 5;
/** Mirrors `COLLAPSED_LINES` in agent/extensions/shared/markdown.ts. */
const COLLAPSED_MARKDOWN_LINES = 10;
/** True for the db-viewer tools this card owns. */
export function isDbQueryTool(toolName: unknown): toolName is string {
    return typeof toolName === "string" && Object.hasOwn(DB_QUERY_TOOL_LABELS, toolName);
}
/**
 * Strip the password out of a connection URI before it reaches the card:
 * `mysql://user:pw@host:3306/db` → `mysql://user:***@host:3306/db`. User, host
 * and database stay (they say *which* database was queried); anything that does
 * not look like a URI is returned unchanged. The userinfo/host split is the last
 * `@` — inside the authority when the URI is well formed, and the last one in the
 * URI otherwise — so a password containing `@`, `/`, `?` or `#` is masked instead
 * of returned raw.
 */
function redactConnectionTarget(raw: string): string {
    const uri = raw.trim();
    const schemeEnd = uri.indexOf("://");
    if (schemeEnd <= 0) return uri;
    const userinfoStart = schemeEnd + 3;
    const pathStart = uri.slice(userinfoStart).search(/[/?#]/);
    const authorityEnd = pathStart < 0 ? uri.length : userinfoStart + pathStart;
    const inAuthority = uri.lastIndexOf("@", authorityEnd);
    const at = inAuthority >= userinfoStart ? inAuthority : uri.lastIndexOf("@");
    if (at <= userinfoStart) return uri;
    const colon = uri.indexOf(":", userinfoStart);
    if (colon < 0 || colon > at) return uri; // no password to hide
    return `${uri.slice(0, userinfoStart)}${uri.slice(userinfoStart, colon)}:***${uri.slice(at)}`;
}
/** Card header target: the redacted connection URI, or the sqlite file path. */
function callTarget(args: Record<string, unknown>, context: BoxedToolContext): string | undefined {
    const connection = args?.connectionString;
    if (typeof connection === "string" && connection.trim()) {
        return redactConnectionTarget(connection);
    }
    const dbPath = args?.dbPath;
    if (typeof dbPath === "string" && dbPath.trim()) {
        return displayPath(dbPath, context);
    }
    return undefined;
}
export function renderDbQueryCall(
    toolName: string,
    args: Record<string, unknown>,
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    noteExecutionStart(context);
    noteBoxedCallState(context);
    const queryLines = (typeof args?.query === "string" ? args.query : "")
        .replace(/\r/g, "")
        .split("\n");
    const shownLines = context.expanded
        ? queryLines.length
        : Math.min(queryLines.length, COLLAPSED_QUERY_LINES);
    const detailLines: string[] = [];
    for (let index = 0; index < shownLines; index++) {
        const prefix = index === 0 ? "> " : "  ";
        detailLines.push(`${theme.fg("dim", prefix)}${queryLines[index] ?? ""}`);
    }
    if (queryLines.length > shownLines) {
        detailLines.push(theme.fg("muted", `... ${queryLines.length - shownLines} more lines`));
    }
    const maxRows = args?.maxRows;
    if (typeof maxRows === "number" && Number.isFinite(maxRows)) {
        detailLines.push(`${theme.fg("dim", "Max rows: ")}${Math.floor(maxRows)}`);
    }
    return renderBoxedToolCall(theme, DB_QUERY_TOOL_LABELS[toolName], detailLines, {
        headerDetail: callTarget(args, context),
        isError: context.isError,
        isPartial: context.isPartial,
        isPending: context.isPartial,
        running: context.executionStarted,
        resultSeen: isResultSeen(context.state),
    });
}
/**
 * db-viewer's result look: pi's Markdown renderer (box tables) with the same
 * 10-line collapse. Errors and empty output stay plain text, as upstream.
 */
function markdownRows(
    text: string,
    expanded: boolean,
    isError: boolean,
): (width: number) => string[] {
    return (width) => {
        if (isError || !text.trim()) return new Text(text, 0, 0).render(width);
        const lines = new Markdown(text, 0, 0, getMarkdownTheme()).render(width);
        if (expanded) {
            const maxExpanded = getToolsRenderConfig().maxExpandedLines;
            if (maxExpanded > 0 && lines.length > maxExpanded) {
                const remaining = lines.length - maxExpanded;
                return [
                    ...lines.slice(0, maxExpanded),
                    `... (${remaining} more lines omitted by render budget)`,
                ];
            }
            return lines;
        }
        if (lines.length <= COLLAPSED_MARKDOWN_LINES) return lines;
        const remaining = lines.length - COLLAPSED_MARKDOWN_LINES;
        return [
            ...lines.slice(0, COLLAPSED_MARKDOWN_LINES),
            `... (${remaining} more lines, expand)`,
        ];
    };
}
/** Data rows in a `formatRowsToMarkdown` table (header and separator are not rows). */
function countTableRows(text: string): number | undefined {
    let tableLines = 0;
    let separatorSeen = false;
    for (const line of text.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed.startsWith("|")) continue;
        tableLines++;
        if (/^\|[\s:|-]+$/.test(trimmed)) separatorSeen = true;
    }
    return separatorSeen && tableLines >= 2 ? tableLines - 2 : undefined;
}
/** ` · N items` — the secondary metric appended after a footer's primary one. */
function countMetric(
    theme: BoxTheme,
    count: number,
    singular: string,
    plural = `${singular}s`,
): string {
    const label = `${count} ${count === 1 ? singular : plural}`;
    return `${theme.fg("dim", " · ")}${theme.fg("dim", label)}`;
}
/** `elapsed · N rows` — the word-count metric would be noise for a table. */
function dbFooter(theme: BoxTheme, context: BoxedToolContext, rows: number | undefined): string {
    const elapsedMs = stateElapsedMs(context);
    const elapsed =
        elapsedMs === undefined ? theme.fg("dim", "--") : formatElapsedMetric(theme, elapsedMs);
    if (rows === undefined) return elapsed;
    return `${elapsed}${countMetric(theme, rows, "row")}`;
}
export function renderDbQueryResult(
    result: BoxedToolResult,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    noteBoxedResultPhase(context, options.isPartial);
    const isError = context.isError;
    const text = getTextOutput(result);
    return renderBoxedToolResult(theme, markdownRows(text, options.expanded, isError), {
        dividerLabel: "Rows",
        footerLines: [dbFooter(theme, context, countTableRows(text))],
        isError,
        isPartial: options.isPartial,
    });
}

// from: ocr-card.ts

/**
 * Boxed card for the OCR tools (`ocr_review`, `ocr_scan`) (fork addition — not vendored pi-style).
 *
 * The OCR extension publishes its live run state through `details` on every
 * partial update and on the settled return. This card reads that state: live
 * action and file rows while running, severity-grouped findings with a metrics
 * footer once it settles. Without it the run falls to the generic fallback,
 * which prints the raw JSON wall and drops `details` entirely.
 */
/** Action rows shown while collapsed; expanding reveals the rest. */
const COLLAPSED_ACTIONS = 12;
/** Findings shown while collapsed; expanding reveals the rest. */
const COLLAPSED_FINDINGS = 3;
/** Call-card detail lines shown while collapsed. */
const COLLAPSED_CALL_LINES = 5;
/**
 * Braille frames for in-flight file rows, same set `bash-display.ts` uses.
 * The shared boxed ticker repaints once a second (that is what keeps elapsed
 * labels live), which is far too coarse for a spinner to read as motion, so a
 * running card drives its own faster repaint through `context.invalidate()`.
 */
const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"] as const;
const SPINNER_INTERVAL_MS = 150;
let spinnerFrameIndex = 0;
let spinnerTimer: ReturnType<typeof setInterval> | undefined;
function startSpinnerTicker(context: BoxedToolContext): void {
    if (spinnerTimer !== undefined) return;
    spinnerTimer = setInterval(() => {
        spinnerFrameIndex = (spinnerFrameIndex + 1) % SPINNER_FRAMES.length;
        context.invalidate();
    }, SPINNER_INTERVAL_MS);
}
function stopSpinnerTicker(): void {
    if (spinnerTimer === undefined) return;
    clearInterval(spinnerTimer);
    spinnerTimer = undefined;
}
// One module-level ticker, so one cleanup: `registerTimer` per start would
// pile up a callback every time a run begins.
registerCleanup(stopSpinnerTicker);
interface OcrActionRow {
    tool: string;
    args?: string;
    ok: boolean;
    ms?: number;
}
interface OcrFileRow {
    path: string;
    comments?: number;
}
interface OcrFindingRow {
    path: string;
    start: number;
    end: number;
    severity: string;
    category: string;
    content: string;
    suggestion?: string;
}
interface OcrResultState {
    findings: OcrFindingRow[];
    filesReviewed: number;
    comments: number;
    totalTokens: number;
    elapsed?: string;
    model?: string;
}
interface OcrCardState {
    mode: string;
    scope?: string;
    files?: OcrFileRow[];
    actions: OcrActionRow[];
    result?: OcrResultState;
    error?: string;
}
/** True for the OCR tools this card owns (`ocr_health` keeps the fallback card). */
export function isOcrTool(toolName: unknown): toolName is string {
    return toolName === "ocr_review" || toolName === "ocr_scan";
}
/**
 * Cosmetic `mode · scope` for the call header, kept local on purpose: the
 * vendored fork stays self-contained and never imports from the OCR extension.
 */
function callScope(toolName: string, args: Record<string, unknown>): string {
    const mode = toolName === "ocr_scan" ? "scan" : "review";
    let scope: string;
    if (mode === "scan") {
        scope = asString(args.path) ?? "whole repo";
    } else if (asString(args.commit)) {
        scope = `commit ${(args.commit as string).slice(0, 7)}`;
    } else {
        const from = asString(args.from);
        const to = asString(args.to);
        scope = from && to ? `${from}..${to}` : "workspace";
    }
    if (args.preview === true) scope += " · preview";
    return `${mode} · ${scope}`;
}
/** Call-card body: model, scope source and background context, max 5 lines collapsed. */
function callDetailLines(
    args: Record<string, unknown>,
    expanded: boolean,
    theme: BoxTheme,
): string[] {
    const lines: string[] = [];
    const model = asString(args.model);
    if (model) lines.push(`${theme.fg("dim", "model: ")}${model}`);
    const commit = asString(args.commit);
    const path = asString(args.path);
    const from = asString(args.from);
    const to = asString(args.to);
    const scopeSource = commit ?? path ?? (from && to ? `${from}..${to}` : undefined);
    if (scopeSource) lines.push(`${theme.fg("dim", "scope: ")}${oneLine(scopeSource, 80)}`);
    const background = asString(args.background);
    if (background) {
        if (expanded) {
            lines.push(theme.fg("dim", "context:"));
            for (const line of background.replace(/\r/g, "").split("\n")) {
                if (line.trim()) lines.push(`  ${line.trim()}`);
            }
        } else {
            lines.push(`${theme.fg("dim", "context: ")}${oneLine(background, 80)}`);
        }
    }
    return expanded ? lines : lines.slice(0, COLLAPSED_CALL_LINES);
}
export function renderOcrCall(
    toolName: string,
    args: Record<string, unknown>,
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    noteExecutionStart(context);
    noteBoxedCallState(context);
    if (!context.isPartial) stopSpinnerTicker();
    // The title is a literal: the name formatter would render "Ocr Review".
    const title = toolName === "ocr_scan" ? "OCR Scan" : "OCR Review";
    let headerDetail = callScope(toolName, args);
    const effort = asString(args.effort);
    if (effort) headerDetail += ` · effort ${effort}`;
    if (headerDetail.length > 63) headerDetail = `${headerDetail.slice(0, 60)}…`;
    return renderBoxedToolCall(theme, title, callDetailLines(args, context.expanded, theme), {
        headerDetail,
        isError: context.isError,
        isPartial: context.isPartial,
        isPending: context.isPartial,
        running: context.executionStarted,
        resultSeen: isResultSeen(context.state),
    });
}
/** `details` arrives untyped through the renderer bridge, so every entry is narrowed before use. */
function readDetails(result: BoxedToolResult | undefined): OcrCardState | undefined {
    const details = result?.details;
    if (!details || typeof details !== "object") return undefined;
    const raw = details as Record<string, unknown>;
    const filesRaw = Array.isArray(raw.files) ? raw.files : undefined;
    const files = filesRaw
        ?.map((entry) => {
            if (!entry || typeof entry !== "object") return undefined;
            const record = entry as Record<string, unknown>;
            const path = asString(record.path);
            if (!path) return undefined;
            const row: OcrFileRow = { path };
            const comments = asNumber(record.comments);
            if (comments !== undefined) row.comments = comments;
            return row;
        })
        .filter((row): row is OcrFileRow => row !== undefined);
    // An empty file list carries no rows, so it counts as absent.
    const fileRows = files && files.length > 0 ? files : undefined;
    const actionsRaw = Array.isArray(raw.actions) ? raw.actions : [];
    const actions: OcrActionRow[] = [];
    for (const entry of actionsRaw) {
        if (!entry || typeof entry !== "object") continue;
        const record = entry as Record<string, unknown>;
        const tool = asString(record.tool);
        if (!tool) continue;
        const action: OcrActionRow = { tool, ok: record.ok === true };
        const args = asString(record.args);
        if (args !== undefined) action.args = args;
        const ms = asNumber(record.ms);
        if (ms !== undefined) action.ms = ms;
        actions.push(action);
    }
    let stateResult: OcrResultState | undefined;
    const resultRaw = raw.result;
    if (resultRaw && typeof resultRaw === "object") {
        const record = resultRaw as Record<string, unknown>;
        const findings: OcrFindingRow[] = [];
        const commentsRaw = Array.isArray(record.findings) ? record.findings : [];
        for (const entry of commentsRaw) {
            if (!entry || typeof entry !== "object") continue;
            const finding = entry as Record<string, unknown>;
            const path = asString(finding.path);
            if (!path) continue;
            findings.push({
                path,
                start: asNumber(finding.start_line) ?? 0,
                end: asNumber(finding.end_line) ?? 0,
                severity: asString(finding.severity) ?? "",
                category: asString(finding.category) ?? "",
                content: asString(finding.content) ?? "",
                suggestion: asString(finding.suggestion_code),
            });
        }
        stateResult = {
            findings,
            filesReviewed: asNumber(record.filesReviewed) ?? 0,
            comments: asNumber(record.comments) ?? findings.length,
            totalTokens: asNumber(record.totalTokens) ?? 0,
            elapsed: asString(record.elapsed),
            model: asString(record.model),
        };
    }
    return {
        mode: asString(raw.mode) ?? "review",
        scope: asString(raw.scope),
        files: fileRows,
        actions,
        result: stateResult,
        error: asString(raw.error),
    };
}
function fileRowLines(
    files: OcrFileRow[],
    glyph: string,
    glyphRole: "warning" | "success" | "error",
    theme: BoxTheme,
    withCounts: boolean,
): string[] {
    return files.map((file) => {
        const count =
            withCounts && file.comments !== undefined
                ? theme.fg(
                      "dim",
                      `  ${file.comments} ${file.comments === 1 ? "comment" : "comments"}`,
                  )
                : "";
        return `${theme.fg(glyphRole, glyph)} ${file.path}${count}`;
    });
}
function applyBudget(lines: string[], expanded: boolean, theme: BoxTheme): string[] {
    const budget = expanded ? getToolsRenderConfig().maxExpandedLines : COLLAPSED_RUN_LINES;
    if (lines.length <= budget) return lines;
    const omitted = lines.length - budget;
    return [
        ...lines.slice(0, budget),
        theme.fg("muted", `… ${omitted} more lines omitted by render budget`),
    ];
}
function severityRole(severity: string): "error" | "warning" | "dim" {
    switch (severity.toLowerCase()) {
        case "high":
        case "critical":
        case "error":
            return "error";
        case "medium":
        case "moderate":
        case "warning":
            return "warning";
        default:
            return "dim";
    }
}
function findingBlockLines(
    finding: OcrFindingRow,
    showSuggestion: boolean,
    expanded: boolean,
    theme: BoxTheme,
): string[] {
    const role = severityRole(finding.severity);
    const location =
        finding.start > 0 ? `${finding.path}:${finding.start}-${finding.end}` : finding.path;
    const lines = [
        `${theme.fg(role, "●")} ${theme.fg(role, finding.severity.toUpperCase() || "?")}  ${theme.fg("accent", finding.category || "review")}  ${theme.fg("dim", location)}`,
    ];
    if (finding.content) {
        for (const line of finding.content.replace(/\r/g, "").split("\n")) {
            if (line.trim()) lines.push(`  ${line.trim()}`);
        }
    }
    // Only the first finding carries its suggestion inline; the rest stay compact.
    if (showSuggestion && finding.suggestion) {
        const { lines: suggestionLines, omitted } = selectRenderLines(
            finding.suggestion,
            expanded ? getToolsRenderConfig().maxExpandedLines : 10,
        );
        lines.push(theme.fg("muted", "┌ suggestion"));
        for (const line of suggestionLines) {
            lines.push(formatToolOutputLine(theme, `│ ${line}`));
        }
        if (omitted > 0) {
            lines.push(theme.fg("muted", `… ${omitted} more lines omitted by render budget`));
        }
        lines.push(theme.fg("muted", "└"));
    }
    return lines;
}
function summaryLine(result: OcrResultState, theme: BoxTheme): string {
    const files = `${result.filesReviewed} ${result.filesReviewed === 1 ? "file" : "files"} reviewed`;
    const comments = `${result.comments} ${result.comments === 1 ? "comment" : "comments"}`;
    return `${theme.fg("text", files)}${theme.fg("dim", " · ")}${theme.fg("text", comments)}`;
}
function settledFooterLines(
    state: OcrCardState,
    result: OcrResultState,
    theme: BoxTheme,
    context: BoxedToolContext,
): string[] {
    const elapsedMs = stateElapsedMs(context);
    const elapsed =
        result.elapsed ??
        (elapsedMs === undefined ? undefined : formatElapsedMetric(theme, elapsedMs));
    const total = Math.max(state.files?.length ?? 0, result.filesReviewed);
    const parts = [
        theme.fg("dim", elapsed ?? "--"),
        theme.fg("dim", `${result.filesReviewed}/${total} files`),
    ];
    if (result.totalTokens > 0) {
        parts.push(theme.fg("dim", `${formatCompactCount(result.totalTokens)} tok`));
    }
    if (result.model) parts.push(theme.fg("dim", result.model));
    return [parts.join(theme.fg("dim", " · "))];
}

function actionRowLines(actions: OcrActionRow[], expanded: boolean, theme: BoxTheme): string[] {
    const maxActions = expanded ? getToolsRenderConfig().maxExpandedLines : COLLAPSED_ACTIONS;
    const shown = actions.length > maxActions ? actions.slice(-maxActions) : actions;
    const omitted = actions.length - shown.length;
    const lines: string[] = [];
    if (omitted > 0) {
        lines.push(theme.fg("muted", `… ${omitted} earlier actions omitted by render budget`));
    }
    for (const action of shown) {
        const glyph = action.ok ? theme.fg("success", "✓") : theme.fg("warning", "▸");
        const args = action.args ? ` ${theme.fg("dim", oneLine(action.args, 80))}` : "";
        const ms =
            action.ms !== undefined
                ? `${theme.fg("dim", " · ")}${formatElapsedMetric(theme, action.ms)}`
                : "";
        lines.push(`${glyph} ${theme.fg("accent", action.tool)}${args}${ms}`);
    }
    return lines;
}

/** Placeholder shown before the first progress line reaches the card. */
function emptyPartialHint(state: OcrCardState): string {
    if (state.scope) return `Running ${state.mode} · ${state.scope} — preparing review…`;
    return `Running ${state.mode} — preparing review…`;
}

function renderPartial(
    state: OcrCardState,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    const body = (contentWidth: number): string[] => {
        void contentWidth;
        const lines: string[] = [];
        const files = state.files ?? [];
        const hasActions = state.actions.length > 0;

        if (state.error) {
            lines.push(theme.fg("error", state.error));
        } else if (hasActions) {
            lines.push(...actionRowLines(state.actions, options.expanded, theme));
        } else if (files.length === 0) {
            lines.push(theme.fg("dim", emptyPartialHint(state)));
        }

        if (!state.error && files.length > 0) {
            if (hasActions) lines.push("", theme.fg("dim", "Files"));
            lines.push(
                ...fileRowLines(files, SPINNER_FRAMES[spinnerFrameIndex], "warning", theme, false),
            );
        }
        return applyBudget(lines, options.expanded, theme);
    };
    startSpinnerTicker(context);
    const fileCount = state.files?.length ?? 0;
    const footer = `${formatBoxedRunningStatus(theme, stateElapsedMs(context))}${
        fileCount > 0 ? countMetric(theme, fileCount, "file") : ""
    }`;
    let dividerLabel = "Status";
    if (state.actions.length > 0) dividerLabel = "Actions";
    else if (fileCount > 0) dividerLabel = "Files";
    return renderBoxedToolResult(theme, body, {
        dividerLabel,
        footerLines: [footer],
        isError: context.isError,
        isPartial: options.isPartial,
    });
}
function renderSettled(
    state: OcrCardState,
    result: OcrResultState,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    const maxFindings = options.expanded
        ? getToolsRenderConfig().maxExpandedLines
        : COLLAPSED_FINDINGS;
    const body = (): string[] => {
        const lines = [summaryLine(result, theme), ""];
        const shown = result.findings.slice(0, maxFindings);
        if (shown.length === 0) {
            lines.push(`${theme.fg("success", "✓")} ${theme.fg("dim", "no findings")}`);
        } else {
            for (const [index, finding] of shown.entries()) {
                if (index > 0) lines.push("");
                lines.push(...findingBlockLines(finding, index === 0, options.expanded, theme));
            }
            if (result.findings.length > shown.length) {
                lines.push(
                    theme.fg(
                        "muted",
                        `… ${result.findings.length - shown.length} more lines omitted by render budget`,
                    ),
                );
            }
        }
        if (state.files !== undefined && state.files.length > 0) {
            lines.push("", theme.fg("dim", "Files"));
            lines.push(...fileRowLines(state.files, "✓", "success", theme, true));
        }
        return applyBudget(lines, options.expanded, theme);
    };
    return renderBoxedToolResult(theme, body, {
        dividerLabel: "Findings",
        footerLines: settledFooterLines(state, result, theme, context),
        isError: context.isError,
        isPartial: options.isPartial,
    });
}
function renderPreview(
    state: OcrCardState,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    const body = (): string[] => {
        const lines =
            state.files && state.files.length > 0
                ? fileRowLines(state.files, "✓", "success", theme, false)
                : [theme.fg("dim", "No output received yet")];
        return applyBudget(lines, options.expanded, theme);
    };
    const elapsedMs = stateElapsedMs(context);
    const footer = [
        `${elapsedMs === undefined ? theme.fg("dim", "--") : formatElapsedMetric(theme, elapsedMs)}${theme.fg("dim", " · ")}${theme.fg("dim", `${state.files?.length ?? 0} files`)}`,
    ];
    return renderBoxedToolResult(theme, body, {
        dividerLabel: "Files",
        footerLines: footer,
        isError: context.isError,
        isPartial: options.isPartial,
    });
}
function renderFailed(
    state: OcrCardState,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
    fallbackError?: string,
): Component {
    const body = (): string[] => {
        const errorText = state.error || fallbackError || "Unknown error";
        const { lines: errorLines, omitted } = selectRenderLines(
            errorText,
            options.expanded ? getToolsRenderConfig().maxExpandedLines : 10,
        );
        const lines = errorLines.map((line) => formatToolOutputLine(theme, line, "error"));
        if (omitted > 0) {
            lines.push(theme.fg("muted", `… ${omitted} more lines omitted by render budget`));
        }
        if (state.files !== undefined && state.files.length > 0) {
            lines.push("", theme.fg("dim", "Files"));
            lines.push(...fileRowLines(state.files, "✗", "error", theme, true));
        }
        return applyBudget(lines, options.expanded, theme);
    };
    const elapsedMs = stateElapsedMs(context);
    const fileCount = state.files?.length ?? 0;
    const footer = [
        `${
            elapsedMs === undefined ? theme.fg("dim", "--") : formatElapsedMetric(theme, elapsedMs)
        }${fileCount > 0 ? countMetric(theme, fileCount, "file") : ""}`,
    ];
    return renderBoxedToolResult(theme, body, {
        dividerLabel: "Error",
        footerLines: footer,
        isError: context.isError,
        isPartial: options.isPartial,
    });
}
export function renderOcrResult(
    result: BoxedToolResult,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    const firstResultPass = noteBoxedResultPhase(context, options.isPartial);
    // Terminal pass: the run is over, so the spinner must not outlive it.
    if (!options.isPartial) stopSpinnerTicker();
    const state = readDetails(result);
    const output = getTextOutput(result);
    if (!state) {
        // No structured payload: fall back to the plain output so the card never
        // renders empty.
        const text = output.trim() || "No output received yet";
        return renderBoxedToolResult(theme, (width) => new Text(text, 0, 0).render(width), {
            dividerLabel: "Output",
            isError: context.isError,
            isPartial: options.isPartial,
        });
    }
    if (options.isPartial && firstResultPass) return EMPTY_RESULT;
    if (options.isPartial) return renderPartial(state, options, theme, context);
    if (context.isError || state.error) {
        return renderFailed(state, options, theme, context, output.trim());
    }
    if (state.result) return renderSettled(state, state.result, options, theme, context);
    // Preview runs publish the seeded file list without a result payload.
    return renderPreview(state, options, theme, context);
}

// from: subagent-card.ts

/**
 * Boxed card for the `subagent` tool (fork addition — not vendored pi-style).
 *
 * The renderer patch replaces every tool's renderer, so subagents' own
 * `renderResult` never ran: a running subagent fell to the generic fallback,
 * which prints the call args (`Agent:/Title:/Task:`) plus the literal content
 * string `(running...)` and drops `details` entirely. This card keeps the
 * fork's box chrome and draws that payload instead — one row per agent, its
 * live tool rows while running, metrics once it settles, and the concatenated
 * output underneath.
 */
const SUBAGENT_TOOL_NAME = "subagent";
/** Call-card task preview before the expand hint, mirroring pi-style's 5-line cap. */
const COLLAPSED_TASK_LINES = 5;
/** Tool rows shown per agent while collapsed; expanding reveals the rest. */
const COLLAPSED_TOOL_ROWS = 6;
/** Result output lines shown while collapsed. */
const COLLAPSED_OUTPUT_LINES = 10;
/**
 * Collapsed line budget for the whole card. Deliberately not `previewLines`
 * (8): a multi-agent run needs its per-agent rows, the live tool rows and the
 * output, and the shared preview budget cut the payload off before the output
 * section could ever appear.
 */
const COLLAPSED_RUN_LINES = 24;
interface SubagentToolRow {
    tool?: unknown;
    args?: unknown;
}
interface SubagentProgress {
    status?: unknown;
    currentTool?: unknown;
    currentToolArgs?: unknown;
    recentTools?: SubagentToolRow[];
    toolCount?: unknown;
    tokens?: unknown;
    durationMs?: unknown;
    lastMessage?: unknown;
    error?: unknown;
}
interface SubagentRow {
    agent?: unknown;
    title?: unknown;
    task?: unknown;
    exitCode?: unknown;
    progress?: SubagentProgress;
}
interface SubagentDetails {
    results?: SubagentRow[];
}
/** True for the `subagent` tool this card owns. */
export function isSubagentTool(toolName: unknown): toolName is string {
    return toolName === SUBAGENT_TOOL_NAME;
}
function asString(value: unknown): string | undefined {
    return typeof value === "string" && value.trim() ? value : undefined;
}
function asNumber(value: unknown): number | undefined {
    return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}
/** `details` arrives untyped through the renderer bridge, so every entry is narrowed before use. */
function readSubagentRows(result: BoxedToolResult | undefined): SubagentRow[] | undefined {
    const details = result?.details;
    if (!details || typeof details !== "object") return undefined;
    const results = (details as SubagentDetails).results;
    if (!Array.isArray(results)) return undefined;
    // Rows are dereferenced throughout this card, so non-objects are dropped here.
    const rows = results.filter(
        (row): row is SubagentRow => typeof row === "object" && row !== null,
    );
    return rows.length > 0 ? rows : undefined;
}
/** Single-line preview: newlines collapsed, cut to `max` characters. */
function oneLine(text: string, max: number): string {
    const flat = text.replace(/\s+/g, " ").trim();
    return flat.length > max ? `${flat.slice(0, max)}…` : flat;
}
/** First `max` logical lines of a task, for the call card. */
function taskPreviewLines(task: string, max: number): string[] {
    return task
        .replace(/\r/g, "")
        .split("\n")
        .slice(0, max)
        .map((line) => line.trim())
        .filter((line) => line.length > 0);
}
/** One entry of the call card: a requested run, or a phase header in hybrid mode. */
type CallItem =
    | { kind: "request"; agent: string; label?: string; task?: string }
    | { kind: "group"; label: string };
function toRequest(raw: unknown): CallItem {
    const item = typeof raw === "object" && raw !== null ? (raw as Record<string, unknown>) : {};
    return {
        kind: "request",
        agent: asString(item.agent) ?? "?",
        label: asString(item.title),
        task: asString(item.task),
    };
}
function agentNames(items: CallItem[]): string[] {
    return items.flatMap((item) => (item.kind === "request" ? [item.agent] : []));
}
/** Flatten the call arguments into the runs being requested, plus a header summary. */
function readCall(args: Record<string, unknown>): { summary: string; items: CallItem[] } {
    const hybrid = Array.isArray(args.hybrid) ? args.hybrid : undefined;
    if (hybrid?.length) {
        const items: CallItem[] = [];
        for (const phase of hybrid) {
            if (phase?.mode === "single") {
                items.push(toRequest(phase));
            } else if (Array.isArray(phase?.tasks)) {
                items.push({ kind: "group", label: `${phase.mode} · ${phase.tasks.length}` });
                for (const task of phase.tasks) items.push(toRequest(task));
            }
        }
        return { summary: `hybrid · ${hybrid.length} phases`, items };
    }
    const chain = Array.isArray(args.chain) ? args.chain : undefined;
    if (chain?.length) {
        const items = chain.map(toRequest);
        return { summary: `chain · ${agentNames(items).join(" → ")}`, items };
    }
    const tasks = Array.isArray(args.tasks) ? args.tasks : undefined;
    if (tasks?.length) {
        const items = tasks.map(toRequest);
        return { summary: `parallel · ${agentNames(items).join(", ")}`, items };
    }
    return { summary: `single · ${asString(args.agent) ?? "?"}`, items: [toRequest(args)] };
}
/** Body lines for the call card: one block per requested agent/task. */
function requestDetailLines(items: CallItem[], expanded: boolean, theme: BoxTheme): string[] {
    const maxLines = expanded ? Number.MAX_SAFE_INTEGER : COLLAPSED_TASK_LINES;
    const lines: string[] = [];
    for (const item of items) {
        if (item.kind === "group") {
            lines.push(theme.fg("dim", item.label));
            continue;
        }
        lines.push(
            `${theme.fg("accent", item.agent)}${item.label ? theme.fg("dim", ` · ${item.label}`) : ""}`,
        );
        for (const line of item.task ? taskPreviewLines(item.task, maxLines) : []) {
            lines.push(`${theme.fg("muted", "  ")}${theme.fg("dim", line)}`);
        }
    }
    return lines;
}
/**
 * Shared with the subagents widget (`subagents/src/render.ts`): only `running`
 * and `pending` come from the reported status, and a terminal row is judged by
 * its exit code, so both surfaces classify the same payload identically.
 */
function rowStatus(row: SubagentRow): "running" | "pending" | "completed" | "failed" {
    const status = asString(row.progress?.status) ?? "running";
    if (status === "running" || status === "pending") return status;
    return row.exitCode === 0 ? "completed" : "failed";
}
function rowGlyph(row: SubagentRow, theme: BoxTheme): string {
    switch (rowStatus(row)) {
        case "running":
            return theme.fg("warning", RUNNING_TITLE_GLYPH);
        case "pending":
            return theme.fg("dim", "○");
        case "completed":
            return theme.fg("success", "✓");
        default:
            return theme.fg("error", "✗");
    }
}
/** Compact tool count, tokens and elapsed for one agent row. */
function rowMetrics(row: SubagentRow, theme: BoxTheme): string {
    const parts: string[] = [];
    const tools = asNumber(row.progress?.toolCount);
    const tokens = asNumber(row.progress?.tokens);
    const durationMs = asNumber(row.progress?.durationMs);
    if (tools) parts.push(`${tools} tools`);
    if (tokens) parts.push(`${formatCompactCount(tokens)} tok`);
    if (durationMs) parts.push(formatElapsedMetric(theme, durationMs));
    return parts.join(theme.fg("dim", " · "));
}
function toolRowLines(row: SubagentRow, expanded: boolean, theme: BoxTheme): string[] {
    const recent = Array.isArray(row.progress?.recentTools) ? row.progress.recentTools : [];
    const current = asString(row.progress?.currentTool);
    const running = rowStatus(row) === "running";
    const limit = expanded ? Number.MAX_SAFE_INTEGER : COLLAPSED_TOOL_ROWS;
    const shown = running && current ? recent.slice(-(limit - 1)) : recent.slice(-limit);
    const hidden = recent.length - shown.length;
    const lines: string[] = [];
    if (hidden > 0) {
        lines.push(
            `${theme.fg("muted", "  ")}${theme.fg("dim", `… ${hidden} earlier tool calls`)}`,
        );
    }
    for (const entry of shown) {
        const name = asString(entry?.tool) ?? "?";
        const args = asString(entry?.args);
        lines.push(
            `${theme.fg("muted", "  ")}${theme.fg("accent", name)}${args ? ` ${theme.fg("dim", oneLine(args, 80))}` : ""}`,
        );
    }
    if (running && current) {
        const args = asString(row.progress?.currentToolArgs);
        lines.push(
            `${theme.fg("muted", "  ")}${theme.fg("warning", "▸ ")}${theme.fg("accent", current)}${args ? ` ${theme.fg("dim", oneLine(args, 80))}` : ""}`,
        );
    }
    return lines;
}
function agentBlockLines(row: SubagentRow, expanded: boolean, theme: BoxTheme): string[] {
    const agent = asString(row.agent) ?? "?";
    const label = asString(row.title) ?? asString(row.task);
    const head = `${rowGlyph(row, theme)} ${theme.fg("toolTitle", agent)}${label ? theme.fg("dim", ` · ${oneLine(label, 60)}`) : ""}`;
    const metrics = rowMetrics(row, theme);
    const lines = [metrics ? `${head} ${theme.fg("dim", "·")} ${metrics}` : head];
    lines.push(...toolRowLines(row, expanded, theme));
    const lastMessage = asString(row.progress?.lastMessage);
    if (lastMessage) {
        lines.push(`${theme.fg("muted", "  ")}${theme.fg("dim", oneLine(lastMessage, 120))}`);
    }
    const error = asString(row.progress?.error);
    if (error) {
        lines.push(`${theme.fg("muted", "  ")}${theme.fg("error", oneLine(error, 120))}`);
    }
    return lines;
}
export function renderSubagentCall(
    args: Record<string, unknown>,
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    noteExecutionStart(context);
    noteBoxedCallState(context);
    const { summary, items } = readCall(args);
    return renderBoxedToolCall(
        theme,
        formatToolName(SUBAGENT_TOOL_NAME),
        requestDetailLines(items, context.expanded, theme),
        {
            headerDetail: summary,
            isError: context.isError,
            isPartial: context.isPartial,
            isPending: context.isPartial,
            running: context.executionStarted,
            resultSeen: isResultSeen(context.state),
        },
    );
}
function footerLines(
    rows: SubagentRow[],
    isPartial: boolean,
    theme: BoxTheme,
    context: BoxedToolContext,
): string[] {
    if (isPartial) {
        return [formatBoxedRunningStatus(theme, stateElapsedMs(context))];
    }
    const elapsedMs = stateElapsedMs(context);
    const ok = rows.filter((row) => rowStatus(row) === "completed").length;
    const tokens = rows.reduce((sum, row) => sum + (asNumber(row.progress?.tokens) ?? 0), 0);
    const parts = [
        elapsedMs === undefined ? theme.fg("dim", "--") : formatElapsedMetric(theme, elapsedMs),
        theme.fg("dim", `${ok}/${rows.length} agents`),
    ];
    if (tokens) parts.push(theme.fg("dim", `${formatCompactCount(tokens)} tok`));
    return [parts.join(theme.fg("dim", " · "))];
}
/** First-partial-pass result: the running call card stands alone. */
const EMPTY_RESULT: Component = Object.freeze({
    invalidate() {},
    render() {
        return [];
    },
});
export function renderSubagentResult(
    result: BoxedToolResult,
    options: { expanded: boolean; isPartial: boolean },
    theme: BoxTheme,
    context: BoxedToolContext,
): Component {
    const firstResultPass = noteBoxedResultPhase(context, options.isPartial);
    const rows = readSubagentRows(result);
    const output = getTextOutput(result);
    if (!rows) {
        // No structured payload: fall back to the plain output so the card never
        // renders empty.
        const text = output.trim() || "No output received yet";
        return renderBoxedToolResult(theme, (width) => new Text(text, 0, 0).render(width), {
            dividerLabel: "Output",
            isError: context.isError,
            isPartial: options.isPartial,
        });
    }
    if (options.isPartial && firstResultPass) return EMPTY_RESULT;
    const budget = options.expanded ? getToolsRenderConfig().maxExpandedLines : COLLAPSED_RUN_LINES;
    const hasOutput = output.trim().length > 0;
    const bodyLines = (contentWidth: number): string[] => {
        const lines: string[] = [];
        for (const [index, row] of rows.entries()) {
            if (index > 0) lines.push("");
            lines.push(...agentBlockLines(row, options.expanded, theme));
        }
        // Settled runs append the concatenated output underneath the rows.
        if (!options.isPartial && hasOutput) {
            lines.push("");
            lines.push(theme.fg("muted", "─".repeat(Math.max(8, contentWidth))));
            const maxOutput = options.expanded ? budget : COLLAPSED_OUTPUT_LINES;
            const { lines: outputLines, omitted } = selectRenderLines(output, maxOutput);
            for (const line of outputLines) {
                lines.push(
                    formatToolOutputLine(theme, line, context.isError ? "error" : "toolOutput"),
                );
            }
            if (omitted > 0 && !options.expanded) {
                lines.push(theme.fg("muted", `… ${omitted} more lines omitted by render budget`));
            }
        }
        if (lines.length > budget) {
            const omitted = lines.length - budget;
            return [
                ...lines.slice(0, budget),
                theme.fg("muted", `… ${omitted} more lines omitted by render budget`),
            ];
        }
        return lines;
    };
    return renderBoxedToolResult(theme, bodyLines, {
        dividerLabel: options.isPartial ? "Agents" : "Run",
        footerLines: footerLines(rows, options.isPartial, theme, context),
        showDivider: options.isPartial ? hasOutput : true,
        isError: context.isError,
        isPartial: options.isPartial,
    });
}
